// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {doodadsdoo} from '../models';
import {unitsdoo} from '../models';
import {forge} from '../models';
import {w3i} from '../models';

export function AddCommentTrigger(arg1:string,arg2:number):Promise<main.TriggerMutationResultDTO>;

export function AddGUITrigger(arg1:string,arg2:number):Promise<main.TriggerMutationResultDTO>;

export function AddScriptTrigger(arg1:string,arg2:number):Promise<main.TriggerMutationResultDTO>;

export function AddTriggerCategory(arg1:string,arg2:number):Promise<main.TriggerMutationResultDTO>;

export function AddTriggerECA(arg1:number,arg2:number,arg3:string,arg4:number):Promise<main.TriggerMutationResultDTO>;

export function AddTriggerNestedECA(arg1:number,arg2:Array<number>,arg3:number,arg4:string,arg5:number):Promise<main.TriggerMutationResultDTO>;

export function AddTriggerVariable(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:string):Promise<main.TriggerMutationResultDTO>;

export function BeginUndoGroup(arg1:string):Promise<void>;

export function BrowseForWC3Install():Promise<string>;

export function CanRedo():Promise<boolean>;

export function CanUndo():Promise<boolean>;

export function CheckConvertToLua():Promise<main.ConvertToLuaResultDTO>;

export function ClearSelection():Promise<main.SelectionDTO>;

export function ClearTriggerParamSubFunction(arg1:number,arg2:Array<number>,arg3:Array<number>):Promise<main.TriggerMutationResultDTO>;

export function CloseMap():Promise<main.MapStatus>;

export function ConvertAndImportModel(arg1:main.ImportModelOptions):Promise<main.ImportModelResult>;

export function ConvertMapToLua():Promise<main.ConvertToLuaResultDTO>;

export function ConvertMapToLuaWithEdits(arg1:boolean,arg2:Array<main.SectionOverride>):Promise<main.ConvertToLuaResultDTO>;

export function ConvertMapToLuaWithOptions(arg1:boolean):Promise<main.ConvertToLuaResultDTO>;

export function ConvertObject(arg1:string,arg2:string,arg3:string):Promise<main.ConvertObjectResult>;

export function CreateCustomObject(arg1:string,arg2:string,arg3:string):Promise<main.CreateCustomObjectResult>;

export function CreateCustomUnit(arg1:string,arg2:string):Promise<main.CreateCustomUnitResult>;

export function CreateDoodad(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number):Promise<number>;

export function DeleteCustomObject(arg1:string,arg2:string):Promise<void>;

export function DeleteCustomUnit(arg1:string):Promise<void>;

export function DeleteTriggerECA(arg1:number,arg2:Array<number>):Promise<main.TriggerMutationResultDTO>;

export function DeleteTriggerNode(arg1:number):Promise<main.TriggerMutationResultDTO>;

export function DiscardTo(arg1:number):Promise<void>;

export function EmitTestCommand(arg1:string):Promise<void>;

export function EndUndoGroup():Promise<void>;

export function ForceQuit():Promise<void>;

export function GameplayConstantsApply(arg1:Array<main.GameplayConstantRow>):Promise<void>;

export function GameplayConstantsGet():Promise<Array<main.GameplayConstantRow>>;

export function GenerateTriggerScript():Promise<main.TriggerScriptResultDTO>;

export function GetBridgeInfo():Promise<main.BridgeInfo>;

export function GetDoodad(arg1:number):Promise<doodadsdoo.Doodad>;

export function GetDoodadTypeIndex():Promise<Record<string, main.DoodadTypeInfo>>;

export function GetMapBytes():Promise<string>;

export function GetMinimapBytes():Promise<main.MinimapDTO>;

export function GetObject(arg1:string,arg2:string):Promise<main.UnitObjectDetail>;

export function GetPathingMap():Promise<main.PathingMapDTO>;

export function GetReforgedMode():Promise<boolean>;

export function GetSelection():Promise<main.SelectionDTO>;

export function GetTerrain():Promise<main.TerrainDTO>;

export function GetTranspilePreview():Promise<main.TranspilePreviewDTO>;

export function GetTrigger(arg1:number):Promise<main.TriggerDetailDTO>;

export function GetTriggerFunctionsMeta():Promise<main.TriggerFunctionsMetaDTO>;

export function GetUnit(arg1:number):Promise<unitsdoo.Entity>;

export function GetUnitObject(arg1:string):Promise<main.UnitObjectDetail>;

export function GetUnitTypeIndex():Promise<Record<string, main.UnitTypeInfo>>;

export function HistoryList():Promise<forge.HistoryState>;

export function HistoryUndoCount():Promise<number>;

export function IsDirty():Promise<boolean>;

export function LaunchInWC3():Promise<void>;

export function ListCampaignLoadingScreens():Promise<Array<main.LoadingScreenOption>>;

export function ListCommandButtons():Promise<Array<main.CommandButtonEntry>>;

export function ListDoodads():Promise<Array<main.DoodadDTO>>;

export function ListImportedLoadingScreens():Promise<Array<string>>;

export function ListObjects(arg1:string):Promise<Array<main.UnitObjectListEntity>>;

export function ListSkyModels():Promise<Array<main.SkyModelOption>>;

export function ListSoundEnvironments():Promise<Array<main.LabeledOption>>;

export function ListTilesetOptions():Promise<Array<main.LabeledOption>>;

export function ListTilesets():Promise<Array<main.TilesetInfoDTO>>;

export function ListTriggerCameras():Promise<Array<main.TriggerCameraInfoDTO>>;

export function ListTriggerDestructableInstances():Promise<Array<main.TriggerDestructableInstanceDTO>>;

export function ListTriggerRegions():Promise<Array<main.TriggerRegionInfoDTO>>;

export function ListTriggerTree():Promise<main.TriggerTreeDTO>;

export function ListTriggerUnitInstances():Promise<Array<main.TriggerUnitInstanceDTO>>;

export function ListUnitObjects():Promise<Array<main.UnitObjectListEntity>>;

export function ListUnits():Promise<Array<main.UnitDTO>>;

export function ListWeathers():Promise<Array<main.LabeledOption>>;

export function LogJS(arg1:string):Promise<void>;

export function MapInfoApply(arg1:Record<string, any>):Promise<void>;

export function MapInfoGet():Promise<w3i.Info>;

export function MoveDoodad(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function MoveTriggerECA(arg1:number,arg2:Array<number>,arg3:number):Promise<main.TriggerMutationResultDTO>;

export function MoveTriggerNode(arg1:number,arg2:number):Promise<main.TriggerMutationResultDTO>;

export function MoveUnit(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function NewWindow():Promise<void>;

export function OpenMap(arg1:string):Promise<main.MapStatus>;

export function OpenMapDialog():Promise<string>;

export function OpenMapFileDialog():Promise<string>;

export function OpenMapInNewWindow(arg1:string):Promise<void>;

export function Redo():Promise<void>;

export function RenameTriggerNode(arg1:number,arg2:string):Promise<main.TriggerMutationResultDTO>;

export function RotateDoodad(arg1:number,arg2:number):Promise<void>;

export function RotateUnit(arg1:number,arg2:number):Promise<void>;

export function SaveMap():Promise<void>;

export function SaveTriggerScript():Promise<main.TriggerScriptResultDTO>;

export function ScaleDoodad(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ScaleUnit(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SearchTriggers(arg1:string,arg2:number):Promise<Array<main.TriggerSearchHitDTO>>;

export function SelectUnit(arg1:number):Promise<main.SelectionDTO>;

export function SetMapHeaderScript(arg1:string):Promise<main.TriggerMutationResultDTO>;

export function SetObjectField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.UnitObjectDetail>;

export function SetReforgedMode(arg1:boolean):Promise<boolean>;

export function SetSelection(arg1:Array<main.SelectionItemDTO>):Promise<main.SelectionDTO>;

export function SetSkyModel(arg1:string):Promise<string>;

export function SetTriggerCustomText(arg1:number,arg2:string):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerDescription(arg1:number,arg2:string):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerECAEnabled(arg1:number,arg2:Array<number>,arg3:boolean):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerEnabled(arg1:number,arg2:boolean):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerInitiallyOn(arg1:number,arg2:boolean):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerParamArray(arg1:number,arg2:Array<number>,arg3:Array<number>,arg4:boolean):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerParamSubFunction(arg1:number,arg2:Array<number>,arg3:Array<number>,arg4:string):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerParamValue(arg1:number,arg2:Array<number>,arg3:Array<number>,arg4:string,arg5:number):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerRunOnInit(arg1:number,arg2:boolean):Promise<main.TriggerMutationResultDTO>;

export function SetTriggerVariable(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:number,arg6:string):Promise<main.TriggerMutationResultDTO>;

export function SetUnitAnimation(arg1:number,arg2:string):Promise<void>;

export function SetUnitObjectField(arg1:string,arg2:string,arg3:string):Promise<main.UnitObjectDetail>;

export function SetWC3InstallPath(arg1:string):Promise<main.WC3InstallStatusDTO>;

export function Status():Promise<main.MapStatus>;

export function SwapTileset(arg1:main.SwapTilesetRequest):Promise<main.TerrainDTO>;

export function TestMap():Promise<void>;

export function Undo():Promise<void>;

export function UndoTo(arg1:number):Promise<void>;

export function WC3InstallStatus():Promise<main.WC3InstallStatusDTO>;
